# Generated by Django 3.2.3 on 2021-05-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('gender', models.CharField(default='', help_text='Пол.', max_length=100, verbose_name='Gender:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Полы',
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('nickname', models.CharField(blank=True, default='', help_text='Псевдоним.', max_length=200, verbose_name='Nickname:')),
                ('email', models.EmailField(blank=True, default='', help_text='E-mail главный.', max_length=200, verbose_name='E-mail:')),
                ('email_first', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 1.', max_length=200, verbose_name='E-mail first:')),
                ('email_second', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 2.', max_length=200, verbose_name='E-mail second:')),
                ('email_third', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 3.', max_length=200, verbose_name='E-mail third:')),
                ('surname', models.CharField(default='', help_text='Фамилия.', max_length=200, verbose_name='Surname:')),
                ('name', models.CharField(default='', help_text='Имя.', max_length=200, verbose_name='Name:')),
                ('middle_name', models.CharField(blank=True, default='', help_text='Отчество.', max_length=200, verbose_name='Middle name:')),
                ('gender', models.ForeignKey(blank=True, help_text='Пол.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='humans_gender', related_query_name='human_gender', to='core.gender', verbose_name='Gender:')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Человеки',
            },
        ),
    ]
