# Generated by Django 3.2.3 on 2021-05-25 15:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('domen', models.CharField(default='', help_text='Домен.', max_length=5, verbose_name='Domen:')),
                ('title', models.CharField(default='', help_text='Страна.', max_length=50, verbose_name='Country:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Стран',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='FrameworkProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('title', models.CharField(default='', help_text='Язык программирвоания.', max_length=100, verbose_name='Framework:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'ФрэймВорк',
                'verbose_name_plural': 'ФрэймВорки',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('gender', models.CharField(default='', help_text='Пол.', max_length=100, verbose_name='Gender:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Полы',
            },
        ),
        migrations.CreateModel(
            name='IntervalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('title', models.CharField(blank=True, default='', help_text='Интервал.', max_length=100, verbose_name='Interval:')),
                ('timeFrom', models.IntegerField(default=8, help_text='Начало работы.', verbose_name='Start:')),
                ('timeTo', models.IntegerField(default=17, help_text='Завершение работы.', verbose_name='Stop:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Времена работы',
            },
        ),
        migrations.CreateModel(
            name='LanguageProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('title', models.CharField(default='', help_text='Язык программирвоания.', max_length=100, verbose_name='Language:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Язык программиирование',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.CreateModel(
            name='LevelLanguageKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('title', models.CharField(default='', help_text='Знание.', max_length=100, verbose_name='Knowledge:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Знание уровеня языка',
                'verbose_name_plural': 'Знание уровней языков',
            },
        ),
        migrations.CreateModel(
            name='LevelLanguageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('suffix', models.CharField(blank=True, default='', help_text='Суффикс.', max_length=2, verbose_name='Suffix:')),
                ('title', models.CharField(default='', help_text='Название.', max_length=100, verbose_name='Title:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Название уровеня языка',
                'verbose_name_plural': 'Названия уровней языков',
            },
        ),
        migrations.CreateModel(
            name='SkillProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('title', models.CharField(default='', help_text='Навыки и умения.', max_length=100, verbose_name='Skills:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Дополнительный навык',
                'verbose_name_plural': 'Дополнительный навыки',
            },
        ),
        migrations.CreateModel(
            name='TimeZoneResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('timezone', models.CharField(default='', help_text='Временная зона города.', max_length=100, verbose_name='Time Zone:')),
                ('hours', models.IntegerField(default=0, help_text='Час +/-.', verbose_name='Time Zone Hours(+/-):')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Тайм Зона',
                'verbose_name_plural': 'Тайм Зоны',
            },
        ),
        migrations.CreateModel(
            name='RateWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('title', models.CharField(blank=True, default='', help_text='Название.', max_length=100, verbose_name='Title:')),
                ('price_dollar', models.IntegerField(default=20, help_text='Цена (в долларах).', verbose_name='Price (USA dollar):')),
                ('price_rub', models.IntegerField(blank=True, default=0, help_text='Цена (в рублях).', verbose_name='Price (RUB):')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
                ('framework', models.ForeignKey(blank=True, help_text='ФрэймВорк.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RateWorks', related_query_name='RateWork', to='core.frameworkprogramming', verbose_name='Framework:')),
                ('language', models.ForeignKey(blank=True, help_text='Язык.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RateWorks', related_query_name='RateWork', to='core.languageprogramming', verbose_name='Language:')),
            ],
            options={
                'verbose_name': 'Цена работы',
                'verbose_name_plural': 'Цены работ',
            },
        ),
        migrations.CreateModel(
            name='LevelLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('CEFR', models.CharField(choices=[('CEFR', 'ДА - В системе'), ('NO CEFR', 'НЕТ - Наша оценка')], default='', help_text='Уровень Мировой ил Наша интерпретация.', max_length=100, verbose_name='CERF ??:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
                ('knowledge', models.ForeignKey(help_text='Знание.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LevelLanguages', related_query_name='LevelLanguage', to='core.levellanguageknowledge', verbose_name='Knowledge:')),
                ('level', models.ForeignKey(help_text='Уровень.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LevelLanguages', related_query_name='LevelLanguage', to='core.levellanguagetitle', verbose_name='Level:')),
            ],
            options={
                'verbose_name': 'Уровень языка',
                'verbose_name_plural': 'Уровни языков',
            },
        ),
        migrations.AddField(
            model_name='frameworkprogramming',
            name='language',
            field=models.ForeignKey(help_text='Язык.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FrameworkProgrammings', related_query_name='FrameworkProgramming', to='core.languageprogramming', verbose_name='Language:'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('title', models.CharField(default='', help_text='Город.', max_length=50, verbose_name='City:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
                ('country', models.ForeignKey(blank=True, help_text='Страна.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', related_query_name='city', to='core.country', verbose_name='Country:')),
                ('timezone', models.ForeignKey(blank=True, help_text='Временная зона.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', related_query_name='city', to='core.timezoneresidence', verbose_name='Time Zone:')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('nickname', models.CharField(blank=True, default='', help_text='Псевдоним.', max_length=200, verbose_name='Nickname:')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Номер телефона.', max_length=128, region=None, verbose_name='Phone:')),
                ('email', models.EmailField(blank=True, default='', help_text='E-mail главный.', max_length=200, verbose_name='E-mail:')),
                ('email_first', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 1 (*@hubbiton.info).', max_length=200, verbose_name='E-mail first:')),
                ('email_second', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 2.', max_length=200, verbose_name='E-mail second:')),
                ('email_third', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 3.', max_length=200, verbose_name='E-mail third:')),
                ('surname', models.CharField(default='', help_text='Фамилия.', max_length=200, verbose_name='Surname:')),
                ('name', models.CharField(default='', help_text='Имя.', max_length=200, verbose_name='Name:')),
                ('middle_name', models.CharField(blank=True, default='', help_text='Отчество.', max_length=200, verbose_name='Middle name:')),
                ('city', models.ForeignKey(help_text='Город.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='humans', related_query_name='human', to='core.city', verbose_name='City:')),
                ('framework_programming', models.ManyToManyField(help_text='ФрэймВорки.', related_name='humans', related_query_name='human', to='core.FrameworkProgramming', verbose_name='Frameworks:')),
                ('gender', models.ForeignKey(help_text='Пол.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='humans', related_query_name='human', to='core.gender', verbose_name='Gender:')),
                ('interval_works', models.ManyToManyField(help_text='Интервалы.', related_name='humans', related_query_name='human', to='core.IntervalWork', verbose_name='Intervals:')),
                ('language_programming', models.ManyToManyField(help_text='Языки.', related_name='humans', related_query_name='human', to='core.LanguageProgramming', verbose_name='Languages:')),
                ('level_english', models.ForeignKey(help_text='Уровень Английского.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='humans', related_query_name='human', to='core.levellanguage', verbose_name='Level English:')),
                ('rate_works', models.ManyToManyField(blank=True, help_text='Цена.', related_name='humans', related_query_name='human', to='core.RateWork', verbose_name='Price:')),
                ('skills_programming', models.ManyToManyField(help_text='Навыки.', related_name='humans', related_query_name='human', to='core.SkillProgramming', verbose_name='Skills:')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Человеки',
                'ordering': ('modified_at',),
                'unique_together': {('phone', 'email', 'email_first')},
            },
        ),
    ]
