# Generated by Django 3.2.3 on 2021-05-23 15:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('title', models.CharField(default='', help_text='Город.', max_length=50, verbose_name='City:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('domen', models.CharField(default='', help_text='Домен.', max_length=5, verbose_name='Domen:')),
                ('title', models.CharField(default='', help_text='Страна.', max_length=50, verbose_name='Country:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Стран',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('gender', models.CharField(default='', help_text='Пол.', max_length=100, verbose_name='Gender:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Полы',
            },
        ),
        migrations.CreateModel(
            name='LevelLanguageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('suffix', models.CharField(blank=True, default='', help_text='Суффикс.', max_length=2, verbose_name='Suffix:')),
                ('title', models.CharField(default='', help_text='Название.', max_length=100, verbose_name='Title:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Название уровеня языка',
                'verbose_name_plural': 'Названия уровней языков',
            },
        ),
        migrations.CreateModel(
            name='TimeZoneResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('timezone', models.CharField(default='', help_text='Временная зона города.', max_length=100, verbose_name='Time Zone:')),
                ('hours', models.IntegerField(default=0, help_text='Час +/-.', verbose_name='Time Zone Hours(+/-):')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Тайм Зона',
                'verbose_name_plural': 'Тайм Зоны',
            },
        ),
        migrations.CreateModel(
            name='LevelLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('CEFR', models.CharField(choices=[('CEFR', 'ДА - В системе'), ('NO CEFR', 'НЕТ - Наша оценка')], default='', help_text='Уровень Мировой ил Наша интерпретация.', max_length=100, verbose_name='CERF ??:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
                ('level', models.ForeignKey(help_text='Уровень.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LevelLanguages', related_query_name='LevelLanguage', to='core.levellanguagetitle', verbose_name='Level:')),
            ],
            options={
                'verbose_name': 'Уровень языка',
                'verbose_name_plural': 'Уровни языков',
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('nickname', models.CharField(blank=True, default='', help_text='Псевдоним.', max_length=200, verbose_name='Nickname:')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Номер телефона.', max_length=128, region=None, verbose_name='Phone:')),
                ('email', models.EmailField(blank=True, default='', help_text='E-mail главный.', max_length=200, verbose_name='E-mail:')),
                ('email_first', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 1 (*@hubbiton.info).', max_length=200, verbose_name='E-mail first:')),
                ('email_second', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 2.', max_length=200, verbose_name='E-mail second:')),
                ('email_third', models.EmailField(blank=True, default='', help_text='E-mail дополнительный 3.', max_length=200, verbose_name='E-mail third:')),
                ('surname', models.CharField(default='', help_text='Фамилия.', max_length=200, verbose_name='Surname:')),
                ('name', models.CharField(default='', help_text='Имя.', max_length=200, verbose_name='Name:')),
                ('middle_name', models.CharField(blank=True, default='', help_text='Отчество.', max_length=200, verbose_name='Middle name:')),
                ('city', models.ForeignKey(help_text='Город.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='humans', related_query_name='human', to='core.city', verbose_name='City:')),
                ('gender', models.ForeignKey(help_text='Пол.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='humans', related_query_name='human', to='core.gender', verbose_name='Gender:')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Человеки',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Страна.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', related_query_name='city', to='core.country', verbose_name='Country:'),
        ),
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(blank=True, help_text='Временная зона.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', related_query_name='city', to='core.timezoneresidence', verbose_name='Time Zone:'),
        ),
    ]
