# Generated by Django 3.2.3 on 2021-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='human',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='human',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='human',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
