# Generated by Django 3.2.3 on 2021-05-25 15:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='E-mail главный.', max_length=200, unique=True, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email_first',
            field=models.EmailField(blank=True, default='', help_text='E-mail дополнительный 1 (*@hubbiton.info).', max_length=200, unique=True, verbose_name='E-mail first:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Номер телефона.', max_length=128, region=None, unique=True, verbose_name='Phone:'),
        ),
    ]
