# Generated by Django 3.2.3 on 2021-05-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210525_1836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='human',
            unique_together=set(),
        ),
    ]
