# Generated by Django 3.2.3 on 2021-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210523_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='date published', verbose_name='Date Published:'),
        ),
    ]
