# Generated by Django 3.2.3 on 2021-05-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210523_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levellanguage',
            name='knowledge',
        ),
        migrations.DeleteModel(
            name='LevelLanguageKnowledge',
        ),
    ]
