# Generated by Django 3.2.3 on 2021-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210523_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelLanguageKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('title', models.CharField(default='', help_text='Знание.', max_length=100, verbose_name='Knowledge:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Знание уровеня языка',
                'verbose_name_plural': 'Знание уровней языков',
            },
        ),
    ]
