# Generated by Django 3.2.3 on 2021-05-23 12:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_human_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Номер телефона.', max_length=128, region=None, verbose_name='Phone:'),
        ),
    ]
