# Generated by Django 3.2.3 on 2021-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_human_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='email_first',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='human',
            name='email_second',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='human',
            name='email_third',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
    ]
