# Generated by Django 3.2.3 on 2021-05-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_levellanguageknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='levellanguage',
            name='knowledge',
            field=models.ForeignKey(help_text='Знание.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LevelLanguages', related_query_name='LevelLanguage', to='core.levellanguageknowledge', verbose_name='Knowledge:'),
        ),
    ]
