# Generated by Django 3.2.3 on 2021-05-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210523_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Человеки'},
        ),
    ]
