# Generated by Django 3.2.3 on 2021-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:'),
        ),
    ]
