# Generated by Django 3.2.3 on 2021-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_human_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezoneresidence',
            old_name='hours',
            new_name='_hours',
        ),
        migrations.AlterField(
            model_name='human',
            name='email_first',
            field=models.EmailField(blank=True, default='', help_text='E-mail #1 (*@hubbiton.info).', max_length=200, unique=True, verbose_name='E-mail first:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email_second',
            field=models.EmailField(blank=True, default='', help_text='E-mail #2.', max_length=200, verbose_name='E-mail second:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email_third',
            field=models.EmailField(blank=True, default='', help_text='E-mail #3.', max_length=200, verbose_name='E-mail third:'),
        ),
        migrations.AlterField(
            model_name='timezoneresidence',
            name='_hours',
            field=models.IntegerField(db_column='hours', default=0, help_text='Час +/-.', verbose_name='Time Zone Hours(+/-):'),
        ),
    ]
