# Generated by Django 3.2.3 on 2021-05-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_levellanguage_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='level_english',
            field=models.ForeignKey(help_text='Уровень Английского.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='humans', related_query_name='human', to='core.levellanguage', verbose_name='Level English:'),
        ),
    ]
