# Generated by Django 3.2.3 on 2021-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210523_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='E-mail главный.', max_length=200, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email_first',
            field=models.EmailField(blank=True, default='', help_text='E-mail дополнительный 1.', max_length=200, verbose_name='E-mail first:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email_second',
            field=models.EmailField(blank=True, default='', help_text='E-mail дополнительный 2.', max_length=200, verbose_name='E-mail second:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email_third',
            field=models.EmailField(blank=True, default='', help_text='E-mail дополнительный 3.', max_length=200, verbose_name='E-mail third:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='Отчество.', max_length=200, verbose_name='Middle name:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(default='', help_text='Имя.', max_length=200, verbose_name='Name:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Псевдоним.', max_length=200, verbose_name='Nickname:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='surname',
            field=models.CharField(default='', help_text='Фамилия.', max_length=200, verbose_name='Surname:'),
        ),
    ]
