# Generated by Django 3.2.3 on 2021-05-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210530_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezoneresidence',
            old_name='_hours',
            new_name='hours',
        ),
    ]
