# Generated by Django 3.2.3 on 2021-05-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_languageprogramming'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageprogramming',
            options={'verbose_name': 'Язык программиирование', 'verbose_name_plural': 'Языки программирования'},
        ),
        migrations.CreateModel(
            name='FrameworkProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('title', models.CharField(default='', help_text='Язык программирвоания.', max_length=100, verbose_name='Framework:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
                ('language', models.ForeignKey(help_text='Город.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FrameworkProgrammings', related_query_name='FrameworkProgramming', to='core.languageprogramming', verbose_name='City:')),
            ],
            options={
                'verbose_name': 'ФрэймВорк',
                'verbose_name_plural': 'ФрэймВорки',
            },
        ),
    ]
