# Generated by Django 3.2.3 on 2021-05-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename__hours_timezoneresidence_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='framework_programming',
            field=models.ManyToManyField(blank=True, help_text='ФрэймВорки.', related_name='humans', related_query_name='human', to='core.FrameworkProgramming', verbose_name='Frameworks:'),
        ),
    ]
