# Generated by Django 3.2.3 on 2021-05-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_human_framework_programming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('modified_at', models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:')),
                ('token', models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='Уникальный токен команды')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
