# Generated by Django 3.2.3 on 2021-05-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210523_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='framework_programming',
            field=models.ManyToManyField(help_text='ФрэймВорки.', null=True, related_name='humans', related_query_name='human', to='core.FrameworkProgramming', verbose_name='Frameworks:'),
        ),
        migrations.AddField(
            model_name='human',
            name='language_programming',
            field=models.ManyToManyField(help_text='Языки.', null=True, related_name='humans', related_query_name='human', to='core.LanguageProgramming', verbose_name='Languages:'),
        ),
        migrations.AlterField(
            model_name='frameworkprogramming',
            name='language',
            field=models.ForeignKey(help_text='Язык.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FrameworkProgrammings', related_query_name='FrameworkProgramming', to='core.languageprogramming', verbose_name='Language:'),
        ),
    ]
