# Generated by Django 3.2.3 on 2021-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210523_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='framework_programming',
            field=models.ManyToManyField(help_text='ФрэймВорки.', related_name='humans', related_query_name='human', to='core.FrameworkProgramming', verbose_name='Frameworks:'),
        ),
    ]
