# Generated by Django 3.2.3 on 2021-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210530_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='active',
            field=models.BooleanField(default=True, help_text='Активность.', verbose_name='Active:'),
        ),
    ]
