# Generated by Django 3.2.3 on 2021-05-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_token_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', related_query_name='city', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='country',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', related_query_name='country', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='frameworkprogramming',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frameworks', related_query_name='framework', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='gender',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genders', related_query_name='gender', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='human',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='humans', related_query_name='human', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='intervalwork',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interval_works', related_query_name='interval_work', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='languageprogramming',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language_programmings', related_query_name='language_programming', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='levellanguage',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_languages', related_query_name='level_language', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='levellanguageknowledge',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_language_knowledges', related_query_name='level_language_knowledge', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='levellanguagetitle',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_language_titles', related_query_name='level_language', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='ratework',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_works', related_query_name='rate_work', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='skillprogramming',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill_programmings', related_query_name='skill_programming', to='core.token', verbose_name='Token:'),
        ),
        migrations.AddField(
            model_name='timezoneresidence',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Токены.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_zone_residences', related_query_name='time_zone_residence', to='core.token', verbose_name='Token:'),
        ),
    ]
