# Generated by Django 3.2.3 on 2021-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_skillsprogramming'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='skills_programming',
            field=models.ManyToManyField(help_text='Навыки.', related_name='humans', related_query_name='human', to='core.SkillsProgramming', verbose_name='Skills:'),
        ),
    ]
