# Generated by Django 3.2.3 on 2021-05-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210530_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, default='', help_text='Токен.', max_length=33, unique=True, verbose_name='Token:'),
        ),
    ]
