# Generated by Django 3.2.3 on 2021-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_human_skills_programming'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('title', models.CharField(blank=True, default='', help_text='Интервал.', max_length=100, verbose_name='Interval:')),
                ('timeFrom', models.IntegerField(default=8, help_text='Начало работы.', verbose_name='Start:')),
                ('timeTo', models.IntegerField(default=17, help_text='Завершение работы.', verbose_name='Stop:')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Времена работы',
            },
        ),
        migrations.AddField(
            model_name='human',
            name='interval_works',
            field=models.ManyToManyField(help_text='Интервалы.', related_name='humans', related_query_name='human', to='core.IntervalWorks', verbose_name='Intervals:'),
        ),
    ]
