# Generated by Django 3.2.3 on 2021-05-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_token_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gender',
            new_name='title',
        ),
    ]
