# Generated by Django 3.2.3 on 2021-05-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210523_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntervalWorks',
            new_name='IntervalWork',
        ),
    ]
