# Generated by Django 3.2.3 on 2021-05-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_intervalworks_intervalwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillsProgramming',
            new_name='SkillProgramming',
        ),
    ]
