# Generated by Django 3.2.3 on 2021-05-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_gender_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='title',
            field=models.CharField(default='', help_text='Пол.', max_length=100, unique=True, verbose_name='Title:'),
        ),
    ]
