# Generated by Django 3.2.3 on 2021-06-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_gender_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='domen',
            field=models.CharField(default='', help_text='Домен.', max_length=5, unique=True, verbose_name='Domen:'),
        ),
    ]
