# Generated by Django 3.2.3 on 2021-05-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_skillsprogramming_skillprogramming'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи.', verbose_name='Date Published:')),
                ('title', models.CharField(blank=True, default='', help_text='Название.', max_length=100, verbose_name='Title:')),
                ('price_dollar', models.IntegerField(default=20, help_text='Цена (в долларах).', verbose_name='Price (USA dollar):')),
                ('price_rub', models.IntegerField(blank=True, default=0, help_text='Цена (в рублях).', verbose_name='Price (RUB):')),
                ('description', models.TextField(blank=True, default='', help_text='Описание.', max_length=400, verbose_name='Description:')),
                ('framework', models.ForeignKey(blank=True, help_text='ФрэймВорк.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RateWorks', related_query_name='RateWork', to='core.frameworkprogramming', verbose_name='Framework:')),
                ('language', models.ForeignKey(blank=True, help_text='Язык.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RateWorks', related_query_name='RateWork', to='core.languageprogramming', verbose_name='Language:')),
            ],
            options={
                'verbose_name': 'Цена работы',
                'verbose_name_plural': 'Цены работ',
            },
        ),
    ]
