# Generated by Django 3.2.3 on 2021-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ratework'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='rate_works',
            field=models.ManyToManyField(blank=True, help_text='Цена.', related_name='humans', related_query_name='human', to='core.RateWork', verbose_name='Price:'),
        ),
    ]
