# Generated by Django 3.2.3 on 2021-05-23 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_human_rate_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='country',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='frameworkprogramming',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='gender',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='human',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='intervalwork',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='languageprogramming',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='levellanguage',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='levellanguageknowledge',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='levellanguagetitle',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='ratework',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='skillprogramming',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AddField(
            model_name='timezoneresidence',
            name='change_date',
            field=models.DateField(default=datetime.datetime, verbose_name='Дата последнего изменения данных'),
        ),
    ]
