# Generated by Django 3.2.3 on 2021-05-23 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210523_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='country',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='frameworkprogramming',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='human',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='intervalwork',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='languageprogramming',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='levellanguage',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='levellanguageknowledge',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='levellanguagetitle',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='ratework',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='skillprogramming',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='timezoneresidence',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 34, 38, 852385, tzinfo=utc), verbose_name='Дата последнего изменения данных'),
        ),
    ]
