# Generated by Django 3.2.3 on 2021-05-23 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210523_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='country',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='frameworkprogramming',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='human',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='intervalwork',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='languageprogramming',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='levellanguage',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='levellanguageknowledge',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='levellanguagetitle',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='ratework',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='skillprogramming',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
        migrations.AlterField(
            model_name='timezoneresidence',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения данных'),
        ),
    ]
