# Generated by Django 3.2.3 on 2021-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210523_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='country',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='frameworkprogramming',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='human',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='intervalwork',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='languageprogramming',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='levellanguage',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='levellanguageknowledge',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='levellanguagetitle',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='ratework',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='skillprogramming',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='timezoneresidence',
            name='change_date',
        ),
    ]
