# Generated by Django 3.2.3 on 2021-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210523_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='country',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='frameworkprogramming',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='intervalwork',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='languageprogramming',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='levellanguage',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='levellanguageknowledge',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='levellanguagetitle',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='ratework',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='skillprogramming',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
        migrations.AlterField(
            model_name='timezoneresidence',
            name='change_date',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения данных.', verbose_name='Date last change:'),
        ),
    ]
