# Generated by Django 3.2.3 on 2021-05-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210523_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ('modified_at',), 'verbose_name': 'Человек', 'verbose_name_plural': 'Человеки'},
        ),
        migrations.AlterField(
            model_name='city',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='country',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='frameworkprogramming',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='human',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='intervalwork',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='languageprogramming',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='levellanguage',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='levellanguageknowledge',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='levellanguagetitle',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='ratework',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='skillprogramming',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
        migrations.AlterField(
            model_name='timezoneresidence',
            name='modified_at',
            field=models.DateField(auto_now=True, help_text='Дата последнего изменения.', verbose_name='Date Modify:'),
        ),
    ]
