# Generated by Django 3.2.3 on 2021-05-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210525_1110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='human',
            unique_together={('phone', 'email', 'email_first')},
        ),
    ]
