# Generated by Django 3.2.3 on 2021-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_human_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='language_programming',
            field=models.ManyToManyField(help_text='Языки.', to='core.LanguageProgramming', verbose_name='Languages:'),
        ),
    ]
