# Generated by Django 3.2.3 on 2021-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_human_language_programming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='language_programming',
            field=models.ManyToManyField(help_text='Языки.', related_name='humans', related_query_name='human', to='core.LanguageProgramming', verbose_name='Languages:'),
        ),
    ]
